# Generated by Django 5.1.2 on 2024-11-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_post_comments_post_created_at_post_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tag',
            new_name='caption',
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='comment.tags'),
        ),
    ]
