# Generated by Django 5.1.2 on 2024-11-24 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_alter_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
    ]
