# Generated by Django 5.1.2 on 2024-11-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0012_alter_vote_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
    ]
